/*
 * SPDX-FileCopyrightText: 2026 Charles Durham
 * SPDX-License-Identifier: MIT
 *
 * MIT License
 *
 * Copyright (c) 2026 Charles Durham
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/* Generated by tests/runtime/embed.py. */
static const char *const numeric_source[] = {
    "\n",
    "typedef unsigned long long U64;\n",
    "struct Slot { U64 data,divisor,count; unsigned kind; int a,b; float v0,v1; };\n",
    "__device__ uint4 philox(U64 block,U64 seed,U64 domain) {\n",
    "    uint4 c=make_uint4((unsigned)block,(unsigned)(block>>32),(unsigned)domain,(unsigned)(domain>>32));\n",
    "    unsigned k0=(unsigned)seed,k1=(unsigned)(seed>>32);\n",
    "    for(unsigned r=0;r<10;++r) {\n",
    "        unsigned hi0=__umulhi(0xd2511f53u,c.x),lo0=0xd2511f53u*c.x;\n",
    "        unsigned hi1=__umulhi(0xcd9e8d57u,c.z),lo1=0xcd9e8d57u*c.z;\n",
    "        c=make_uint4(hi1^c.y^k0,lo1,hi0^c.w^k1,lo0);\n",
    "        k0+=0x9e3779b9u;k1+=0xbb67ae85u;\n",
    "    }\n",
    "    return c;\n",
    "}\n",
    "__device__ float unit(unsigned x) { return ((float)(x>>9)+0.5f)*0.00000011920928955078125f; }\n",
    "extern \"C\" __global__ void grammar_rng(float *out,U64 count,U64 seed,U64 stream,unsigned normal) {\n",
    "    for(U64 b=(U64)blockIdx.x*blockDim.x+threadIdx.x;b<(count+3)/4;b+=(U64)gridDim.x*blockDim.x) {\n",
    "        uint4 bits=philox(b,seed,(stream<<1)|normal);\n",
    "        float u[4]={unit(bits.x),unit(bits.y),unit(bits.z),unit(bits.w)};\n",
    "        if(normal) for(unsigned p=0;p<4;p+=2) {\n",
    "            float radius=sqrtf(-2.0f*logf(u[p])),s,c;\n",
    "            sincosf(6.2831853071795864769f*u[p+1],&s,&c);\n",
    "            u[p]=radius*c;u[p+1]=radius*s;\n",
    "        }\n",
    "        for(unsigned j=0;j<4;++j) if(4*b+j<count) out[4*b+j]=u[j];\n",
    "    }\n",
    "}\n",
    "extern \"C\" __global__ void grammar_prelude(const Slot *slots,float *out,unsigned nslots,unsigned systems,U64 start,unsigned banks) {\n",
    "    for(U64 item=(U64)blockIdx.x*blockDim.x+threadIdx.x;item<(U64)systems*banks;item+=(U64)gridDim.x*blockDim.x) {\n",
    "        unsigned sys=item/banks;U64 bank=start+item%banks;float *row=out+item*nslots;\n",
    "        // Dependencies are fixed/grid slots, and need not precede the RNG slot.\n",
    "        for(unsigned s=0;s<nslots;++s) {\n",
    "            Slot d=slots[sys*nslots+s];\n",
    "            if(d.kind==0) row[s]=d.v0;\n",
    "            else row[s]=((const float*)d.data)[(bank/d.divisor)%d.count];\n",
    "        }\n",
    "        for(unsigned s=0;s<nslots;++s) {\n",
    "            Slot d=slots[sys*nslots+s];\n",
    "            if(d.kind<2) continue;\n",
    "            float u=row[s];\n",
    "            float a=d.a<0?d.v0:row[d.a],b=d.b<0?d.v1:row[d.b];\n",
    "            float v=u;\n",
    "            if(d.kind==2) v=a*u+b;\n",
    "            if(d.kind==3) v=(1.0f-u)*a+u*b;\n",
    "            if(d.kind==4) v=a*u+b;\n",
    "            if(d.kind==5) v=expf((1.0f-u)*logf(a)+u*logf(b));\n",
    "            row[s]=v;\n",
    "        }\n",
    "    }\n",
    "}\n",
    "struct Winner { float mse; unsigned reserved; U64 index; };\n",
    "extern \"C\" __global__ void grammar_consume(float *scores,const Winner *w,U64 count) {\n",
    "    for(U64 i=(U64)blockIdx.x*blockDim.x+threadIdx.x;i<count;i+=(U64)gridDim.x*blockDim.x)\n",
    "        if(w[i].index!=~0ull) scores[w[i].index]=3.40282346638528859812e38f;\n",
    "}\n",
};
