/*
 * SPDX-FileCopyrightText: 2026 Charles Durham
 * SPDX-License-Identifier: MIT
 *
 * MIT License
 *
 * Copyright (c) 2026 Charles Durham
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/* Native LM numerical body. Width one preserves the service algorithm;
 * cooperative widths distribute sensitivities, normal equations and Cholesky. */
#include "o_odezza_internal.h"
#include "o_writer.h"
static const char *const o_lm_body_0[] = {
    "/* Generated trajectory-LM CUDA template. Do not edit by hand.\n",
    " * ownership: FIT_THREAD_COUNT lanes own one toggle permutation and parameter start\n",
    " * integration: resident RK4 over runtime ragged, irregular trajectories\n",
    " * differentiation: specialized local RHS partials and CUDA sensitivity propagation\n",
    " * optimization: damped LM with in-kernel Cholesky retries and proposal evaluation\n",
    " * specialization: operand-bounded primal and derivative sites replicated across fit lanes\n",
    " */\n",
    "\n",
    "extern \"C\" __global__ void odezza_trajectory_lm(\n",
    "    const float *__restrict__ starts,\n",
    "    unsigned long long start_count,\n",
    "    const unsigned int *__restrict__ trajectory_offsets,\n",
    "    const float *__restrict__ trajectory_times,\n",
    "    const float *__restrict__ reference_data,\n",
    "    const float *__restrict__ reference_weights,\n",
    "    unsigned int trajectory_count,\n",
    "    unsigned int trajectory_point_count,\n",
    "    unsigned int active_toggle_count,\n",
    "    unsigned int steps_per_interval,\n",
    "    unsigned int max_lm_iterations,\n",
    "    unsigned int max_damping_attempts,\n",
    "    float initial_damping,\n",
    "    const float *__restrict__ lower_bounds,\n",
    "    const float *__restrict__ upper_bounds,\n",
    "    float maximum_relative_step,\n",
    "    float target_mse,\n",
    "    float *__restrict__ constants_out,\n",
    "    float *__restrict__ initial_mse_out,\n",
    "    float *__restrict__ mse_out,\n",
    "    unsigned int *__restrict__ iterations_out,\n",
    "    unsigned int *__restrict__ accepted_steps_out,\n",
    "    unsigned int *__restrict__ factorization_attempts_out,\n",
    "    unsigned int *__restrict__ evaluations_out,\n",
    "    unsigned int *__restrict__ invalid_evaluations_out\n",
    ") {\n",
    "    if (start_count == 0ull || trajectory_count == 0u || trajectory_point_count < trajectory_count ||\n",
    "        active_toggle_count > 32u || steps_per_interval == 0u || max_lm_iterations == 0u ||\n",
    "        max_damping_attempts == 0u || !isfinite(initial_damping) || initial_damping <= 0.0f || blockDim.x != 32u) return;\n",
    "\n",
    "    const unsigned long long permutation_count = 1ull << active_toggle_count;\n",
    "    if (start_count > 0xffffffffffffffffull / permutation_count) return;\n",
    "    const unsigned long long fit_count = start_count * permutation_count;\n",
    "    const unsigned int lm_fit_lane = threadIdx.x & (ODEZZA_LM_FIT_THREAD_COUNT - 1u);\n",
    "    const unsigned int lm_fit_base = threadIdx.x - lm_fit_lane;\n",
    "    const unsigned int lm_fit_mask = ODEZZA_LM_FIT_THREAD_COUNT == 32\n",
    "        ? 0xffffffffu\n",
    "        : (unsigned int)(((1ull << ODEZZA_LM_FIT_THREAD_COUNT) - 1ull) << lm_fit_base);\n",
    "    const unsigned long long global_thread = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;\n",
    "    const unsigned long long fit = global_thread / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "\n",
    "    const unsigned int reference_float_count = ODEZZA_LM_STATE_COUNT * trajectory_point_count;\n",
    "    extern __shared__ unsigned int shared_words[];\n",
    "    float *reference = reinterpret_cast<float *>(shared_words);\n",
    "    float *weights = reference + reference_float_count;\n",
    "    float *step_sizes = weights + reference_float_count;\n",
    "    unsigned int *offsets = reinterpret_cast<unsigned int *>(step_sizes + trajectory_point_count);\n",
    "    for (unsigned int index = threadIdx.x; index < reference_float_count; index += blockDim.x) {\n",
    "        reference[index] = reference_data[index];\n",
    "        weights[index] = reference_weights[index];\n",
    "    }\n",
    "    for (unsigned int index = threadIdx.x; index < trajectory_point_count; index += blockDim.x) {\n",
    "        step_sizes[index] = index == 0u\n",
    "            ? 0.0f\n",
    "            : (trajectory_times[index] - trajectory_times[index - 1u]) / (float)steps_per_interval;\n",
    "    }\n",
    "    for (unsigned int index = threadIdx.x; index <= trajectory_count; index += blockDim.x) {\n",
    "        offsets[index] = trajectory_offsets[index];\n",
    "    }\n",
    "    __syncthreads();\n",
    "    if (fit >= fit_count) return;\n",
    "\n",
    "    const unsigned int permutation = (unsigned int)fit;\n",
    "    const float lm_permutation_input = __uint_as_float(permutation);\n",
    "    const unsigned long long start_index = fit >> active_toggle_count;\n",
    "    if (lm_fit_lane == 0u) initial_mse_out[fit] = 3.402823466e+38f;\n",
    "\n",
    "    float parameters[ODEZZA_LM_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "    for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "        parameters[parameter] = starts[start_index * ODEZZA_LM_PARAMETER_COUNT + parameter];\n",
    "    }\n",
    "    float lambda = fminf(fmaxf(initial_damping, 1.0e-8f), 1.0e8f);\n",
    "    float current_sse = 3.402823466e+38f;\n",
    "    unsigned int current_residual_count = 0u;\n",
    "    unsigned int completed_iterations = 0u;\n",
    "    unsigned int accepted_steps = 0u;\n",
    "    unsigned int factorization_attempts = 0u;\n",
    "    int optimizer_valid = 1;\n",
    "    unsigned int evaluations = 0u, invalid_evaluations = 0u;\n",
    "\n",
    "    for (unsigned int lm_iteration = 0u;\n",
    "         lm_iteration < max_lm_iterations && optimizer_valid;\n",
    "         ++lm_iteration) {\n",
    "#if ODEZZA_LM_FIT_THREAD_COUNT > 1\n",
    "        float local_optimizer[ODEZZA_LM_LOCAL_OPTIMIZER_COUNT];\n",
    "        float proposal[ODEZZA_LM_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "        for (int index = 0; index < ODEZZA_LM_LOCAL_OPTIMIZER_COUNT; ++index) local_optimizer[index] = 0.0f;\n",
    "#else\n",
    "        float gradient[ODEZZA_LM_PARAMETER_COUNT];\n",
    "        float gram[ODEZZA_LM_GRAM_COUNT];\n",
    "        float proposal[ODEZZA_LM_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "        for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) gradient[parameter] = 0.0f;\n",
    "#pragma unroll\n",
    "        for (int index = 0; index < ODEZZA_LM_GRAM_COUNT; ++index) gram[index] = 0.0f;\n",
    "#endif\n",
    "        int accepted = 0;\n",
    "\n",
    "        for (unsigned int phase = 0u; phase <= max_damping_attempts && !accepted; ++phase) {\n",
    "            const int statistics_phase = phase == 0u;\n",
    "            int proposal_ready = statistics_phase;\n",
    "            if (!statistics_phase) {\n",
    "                ++factorization_attempts;\n",
    "#if ODEZZA_LM_FIT_THREAD_COUNT > 1\n",
    "\n",
    "                float local_factor[ODEZZA_LM_LOCAL_FACTOR_COUNT] = {};\n",
    "                float local_solve[ODEZZA_LM_LOCAL_SOLVE_COUNT] = {};\n",
    "\n",
    "#pragma unroll\n",
    "                for (int gram_index = 0; gram_index < ODEZZA_LM_GRAM_COUNT; ++gram_index) {\n",
    "                    const int source_index = ODEZZA_LM_PARAMETER_COUNT + gram_index;\n",
    "                    const int source_lane = source_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                    const int source_local = source_index / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                    const float value = __shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_optimizer[source_local],\n",
    "                        source_lane,\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "                    const int factor_lane = gram_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                    if (lm_fit_lane == (unsigned int)factor_lane) {\n",
    "                        local_factor[gram_index / ODEZZA_LM_FIT_THREAD_COUNT] = value;\n",
    "                    }\n",
    "                }\n",
    "#pragma unroll\n",
    "                for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "                    const int owner = row & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                    const int local = row / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                    const float value = -__shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_optimizer[local],\n",
    "                        owner,\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "                    if (lm_fit_lane == (unsigned int)owner) local_solve[local] = value;\n",
    "                }\n",
    "                __syncwarp(lm_fit_mask);\n",
    "\n",
    "                int factor_ok = 1;\n",
    "#pragma unroll\n",
    "                for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "#pragma unroll\n",
    "                    for (int column = 0; column <= row; ++column) {\n",
    "                        const int gram_index = column * ODEZZA_LM_PARAMETER_COUNT\n",
    "                            - column * (column - 1) / 2 + row - column;\n",
    "                        const int owner = gram_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                        const int local = gram_index / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                        float sum = __shfl_sync(\n",
    "                            lm_fit_mask,\n",
    "                            local_factor[local],\n",
    "                            owner,\n",
    "                            ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                        );\n",
    "                        if (row == column) sum += lambda * fmaxf(fabsf(sum), 1.0e-8f);\n",
    "#pragma unroll\n",
    "                        for (int k = 0; k < column; ++k) {\n",
    "                            const int row_index = k * ODEZZA_LM_PARAMETER_COUNT\n",
    "                                - k * (k - 1) / 2 + row - k;\n",
    "                            const int column_index = k * ODEZZA_LM_PARAMETER_COUNT\n",
    "                                - k * (k - 1) / 2 + column - k;\n",
    "                            const float row_value = __shfl_sync(\n",
    "                                lm_fit_mask,\n",
    "                                local_factor[row_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                                row_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                                ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                            );\n",
    "                            const float column_value = __shfl_sync(\n",
    "                                lm_fit_mask,\n",
    "                                local_factor[column_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                                column_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                                ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                            );\n",
    "                            sum = fmaf(-row_value, column_value, sum);\n",
    "                        }\n",
    "                        float factor_value;\n",
    "                        if (row == column) {\n",
    "                            const int pivot_ok = factor_ok && isfinite(sum) && sum > 1.0e-12f;\n",
    "                            factor_value = pivot_ok ? sqrtf(sum) : 1.0f;\n",
    "                            factor_ok = pivot_ok;\n",
    "                        } else {\n",
    "                            const int diagonal_index = column * ODEZZA_LM_PARAMETER_COUNT\n",
    "                                - column * (column - 1) / 2;\n",
    "                            const float diagonal = __shfl_sync(\n",
    "                                lm_fit_mask,\n",
    "                                local_factor[diagonal_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                                diagonal_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                                ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                            );\n",
    "                            factor_value = factor_ok ? sum / diagonal : 0.0f;\n",
    "                            factor_ok = factor_ok && isfinite(factor_value);\n",
    "                        }\n",
    "                        if (lm_fit_lane == (unsigned int)owner) local_factor[local] = factor_value;\n",
    "                        __syncwarp(lm_fit_mask);\n",
    "                    }\n",
    "                }\n",
    "\n",
    "#pragma unroll\n",
    "                for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "                    const int owner = row & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                    const int local = row / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                    float value = __shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_solve[local],\n",
    "                        owner,\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "#pragma unroll\n",
    "                    for (int k = 0; k < row; ++k) {\n",
    "                        const int factor_index = k * ODEZZA_LM_PARAMETER_COUNT\n",
    "                            - k * (k - 1) / 2 + row - k;\n",
    "                        const float factor_value = __shfl_sync(\n",
    "                            lm_fit_mask,\n",
    "                            local_factor[factor_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                            factor_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                            ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                        );\n",
    "                        const float solved = __shfl_sync(\n",
    "                            lm_fit_mask,\n",
    "                            local_solve[k / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                            k & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                            ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                        );\n",
    "                        value = fmaf(-factor_value, solved, value);\n",
    "                    }\n",
    "                    const int diagonal_index = row * ODEZZA_LM_PARAMETER_COUNT\n",
    "                        - row * (row - 1) / 2;\n",
    "                    const float diagonal = __shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_factor[diagonal_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                        diagonal_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "                    const float solved = factor_ok ? value / diagonal : 0.0f;\n",
    "                    factor_ok = factor_ok && isfinite(solved);\n",
    "                    if (lm_fit_lane == (unsigned int)owner) local_solve[local] = solved;\n",
    "                    __syncwarp(lm_fit_mask);\n",
    "                }\n",
    "\n",
    "#pragma unroll\n",
    "                for (int reverse = 0; reverse < ODEZZA_LM_PARAMETER_COUNT; ++reverse) {\n",
    "                    const int row = ODEZZA_LM_PARAMETER_COUNT - 1 - reverse;\n",
    "                    const int owner = row & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                    const int local = row / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                    float value = __shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_solve[local],\n",
    "                        owner,\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "#pragma unroll\n",
    "                    for (int k = row + 1; k < ODEZZA_LM_PARAMETER_COUNT; ++k) {\n",
    "                        const int factor_index = row * ODEZZA_LM_PARAMETER_COUNT\n",
    "                            - row * (row - 1) / 2 + k - row;\n",
    "                        const float factor_value = __shfl_sync(\n",
    "                            lm_fit_mask,\n",
    "                            local_factor[factor_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                            factor_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                            ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                        );\n",
    "                        const float delta_value = __shfl_sync(\n",
    "                            lm_fit_mask,\n",
    "                            local_solve[k / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                            k & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                            ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                        );\n",
    "                        value = fmaf(-factor_value, delta_value, value);\n",
    "                    }\n",
    "                    const int diagonal_index = row * ODEZZA_LM_PARAMETER_COUNT\n",
    "                        - row * (row - 1) / 2;\n",
    "                    const float diagonal = __shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_factor[diagonal_index / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                        diagonal_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "                    const float delta_value = factor_ok ? value / diagonal : 0.0f;\n",
    "                    factor_ok = factor_ok && isfinite(delta_value);\n",
    "                    if (lm_fit_lane == (unsigned int)owner) local_solve[local] = delta_value;\n",
    "                    __syncwarp(lm_fit_mask);\n",
    "                }\n",
    "\n",
    "#pragma unroll\n",
    "                for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "                    const float delta_value = __shfl_sync(\n",
    "                        lm_fit_mask,\n",
    "                        local_solve[parameter / ODEZZA_LM_FIT_THREAD_COUNT],\n",
    "                        parameter & (ODEZZA_LM_FIT_THREAD_COUNT - 1),\n",
    "                        ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                    );\n",
    "                    proposal[parameter] = parameters[parameter] + delta_value;\n",
    "                    factor_ok = factor_ok && isfinite(proposal[parameter]);\n",
    "                }\n",
    "                proposal_ready = factor_ok;\n",
    "#else\n",
    "                float factor[ODEZZA_LM_PARAMETER_COUNT * ODEZZA_LM_PARAMETER_COUNT];\n",
    "                float solve_rhs[ODEZZA_LM_PARAMETER_COUNT];\n",
    "                float delta[ODEZZA_LM_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "                for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "#pragma unroll\n",
    "                    for (int column = 0; column < ODEZZA_LM_PARAMETER_COUNT; ++column) {\n",
    "                        const int low = row < column ? row : column;\n",
    "                        const int high = row < column ? column : row;\n",
    "                        const int gram_index = low * ODEZZA_LM_PARAMETER_COUNT\n",
    "                            - low * (low - 1) / 2 + high - low;\n",
    "                        factor[row * ODEZZA_LM_PARAMETER_COUNT + column] = gram[gram_index];\n",
    "                    }\n",
    "                    solve_rhs[row] = -gradient[row];\n",
    "                }\n",
    "\n",
    "                int factor_ok = 1;\n",
    "#pragma unroll\n",
    "                for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "#pragma unroll\n",
    "                    for (int column = 0; column <= row; ++column) {\n",
    "                        float sum = factor[row * ODEZZA_LM_PARAMETER_COUNT + column];\n",
    "                        if (row == column) sum += lambda * fmaxf(fabsf(sum), 1.0e-8f);\n",
    "#pragma unroll\n",
    "                        for (int k = 0; k < column; ++k) {\n",
    "                            sum = fmaf(\n",
    "                                -factor[row * ODEZZA_LM_PARAMETER_COUNT + k],\n",
    "                                factor[column * ODEZZA_LM_PARAMETER_COUNT + k],\n",
    "                                sum\n",
    "                            );\n",
    "                        }\n",
    "                        if (row == column) {\n",
    "                            const int pivot_ok = factor_ok && isfinite(sum) && sum > 1.0e-12f;\n",
    "                            factor[row * ODEZZA_LM_PARAMETER_COUNT + column] = pivot_ok ? sqrtf(sum) : 1.0f;\n",
    "                            factor_ok = pivot_ok;\n",
    "                        } else {\n",
    "                            const float value = factor_ok\n",
    "                                ? sum / factor[column * ODEZZA_LM_PARAMETER_COUNT + column]\n",
    "                                : 0.0f;\n",
    "                            factor[row * ODEZZA_LM_PARAMETER_COUNT + column] = value;\n",
    "                            factor_ok = factor_ok && isfinite(value);\n",
    "                        }\n",
    "                    }\n",
    "                }\n",
    "\n",
    "#pragma unroll\n",
    "                for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "                    float value = solve_rhs[row];\n",
    "#pragma unroll\n",
    "                    for (int k = 0; k < row; ++k) {\n",
    "                        value = fmaf(-factor[row * ODEZZA_LM_PARAMETER_COUNT + k], solve_rhs[k], value);\n",
    "                    }\n",
    "                    solve_rhs[row] = factor_ok\n",
    "                        ? value / factor[row * ODEZZA_LM_PARAMETER_COUNT + row]\n",
    "                        : 0.0f;\n",
    "                    factor_ok = factor_ok && isfinite(solve_rhs[row]);\n",
    "                }\n",
    "\n",
    "#pragma unroll\n",
    "                for (int reverse = 0; reverse < ODEZZA_LM_PARAMETER_COUNT; ++reverse) {\n",
    "                    const int row = ODEZZA_LM_PARAMETER_COUNT - 1 - reverse;\n",
    "                    float value = solve_rhs[row];\n",
    "#pragma unroll\n",
    "                    for (int k = row + 1; k < ODEZZA_LM_PARAMETER_COUNT; ++k) {\n",
    "                        value = fmaf(-factor[k * ODEZZA_LM_PARAMETER_COUNT + row], delta[k], value);\n",
    "                    }\n",
    "                    delta[row] = factor_ok\n",
    "                        ? value / factor[row * ODEZZA_LM_PARAMETER_COUNT + row]\n",
    "                        : 0.0f;\n",
    "                    factor_ok = factor_ok && isfinite(delta[row]);\n",
    "                }\n",
    "\n",
    "#pragma unroll\n",
    "                for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "                    proposal[parameter] = parameters[parameter] + delta[parameter];\n",
    "                    factor_ok = factor_ok && isfinite(proposal[parameter]);\n",
    "                }\n",
    "                proposal_ready = factor_ok;\n",
    "\n",
    "#endif\n",
    "                if (proposal_ready) {\n",
    "#pragma unroll\n",
    "                    for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "                        const float limit = maximum_relative_step * fmaxf(1.0f, fabsf(parameters[parameter]));\n",
    "                        const float step = fminf(limit, fmaxf(-limit, proposal[parameter] - parameters[parameter]));\n",
    "                        proposal[parameter] = fminf(upper_bounds[parameter], fmaxf(lower_bounds[parameter], parameters[parameter] + step));\n",
    "                    }\n",
    "                }\n",
    "\n",
    "                if (!proposal_ready) {\n",
    "                    lambda = fminf(lambda * 10.0f, 1.0e8f);\n",
    "                    continue;\n",
    "                }\n",
    "            }\n",
    "\n",
    "            ++evaluations;\n",
    "            float evaluation_parameters[ODEZZA_LM_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "            for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "                evaluation_parameters[parameter] = statistics_phase\n",
    "                    ? parameters[parameter]\n",
    "                    : proposal[parameter];\n",
    "            }\n",
    "\n",
    "            float evaluated_sse = 0.0f;\n",
    "            unsigned int evaluated_residual_count = 0u;\n",
    "            unsigned int expected_start = 0u;\n",
    "            int evaluated_valid = proposal_ready;\n",
    "            float sensitivities[ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "            for (int index = 0; index < ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT; ++index) {\n",
    "                sensitivities[index] = 0.0f;\n",
    "            }\n",
    "\n",
    "            for (unsigned int trajectory = 0u; trajectory < trajectory_count && evaluated_valid; ++trajectory) {\n",
    "                const unsigned int point_begin = offsets[trajectory];\n",
    "                const unsigned int point_end = offsets[trajectory + 1u];\n",
    "                if (point_begin != expected_start || point_end <= point_begin || point_end > trajectory_point_count) {\n",
    "                    evaluated_valid = 0;\n",
    "                    break;\n",
    "                }\n",
    "                expected_start = point_end;\n",
    "                float state[ODEZZA_LM_STATE_COUNT];\n",
    "#pragma unroll\n",
    "                for (int component = 0; component < ODEZZA_LM_STATE_COUNT; ++component) {\n",
    "                    state[component] = reference[component * trajectory_point_count + point_begin];\n",
    "                }\n",
    "#pragma unroll\n",
    "                for (int index = 0; index < ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT; ++index) {\n",
    "                    sensitivities[index] = 0.0f;\n",
    "                }\n",
    "\n",
    "                for (unsigned int point = point_begin + 1u; point < point_end && evaluated_valid; ++point) {\n",
    "                    const float h = step_sizes[point];\n",
    "                    evaluated_valid = evaluated_valid && isfinite(h) && h > 0.0f;\n",
    "                    const float half_h = 0.5f * h;\n",
    "                    const float sixth_h = h / 6.0f;\n",
    "\n",
    "                    for (unsigned int step = 0u; step < steps_per_interval; ++step) {\n",
    "                        float base_state[ODEZZA_LM_STATE_COUNT];\n",
    "                        float stage_state[ODEZZA_LM_STATE_COUNT];\n",
    "                        float sum_state[ODEZZA_LM_STATE_COUNT];\n",
    "                        float stage_sensitivity[ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT];\n",
    "                        float sum_sensitivity[ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "                        for (int component = 0; component < ODEZZA_LM_STATE_COUNT; ++component) {\n",
    "                            base_state[component] = state[component];\n",
    "                            stage_state[component] = state[component];\n",
    "                            sum_state[component] = 0.0f;\n",
    "                        }\n",
    "#pragma unroll\n",
    "                        for (int index = 0; index < ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT; ++index) {\n",
    "                            stage_sensitivity[index] = sensitivities[index];\n",
    "                            sum_sensitivity[index] = 0.0f;\n",
    "                        }\n",
    "\n",
    "#pragma unroll 1\n",
    "                        for (int rk_stage = 0; rk_stage < 4; ++rk_stage) {\n",
    NULL};
OdezzaResult o_lm_write_body_0(OWriter *w) {
    size_t i;
    for (i = 0; o_lm_body_0[i]; ++i)
        O_RETURN_IF_ERROR(o_writer_cstr(w, o_lm_body_0[i]));
    return ODEZZA_SUCCESS;
}
static const char *const o_lm_body_1[] = {
    "\n",
    "\n",
    "                            if (rk_stage != 3) {\n",
    "                                const float stage_h = rk_stage == 2 ? h : half_h;\n",
    "#pragma unroll\n",
    "                                for (int component = 0; component < ODEZZA_LM_STATE_COUNT; ++component) {\n",
    "                                    stage_state[component] = fmaf(stage_h, rhs[component], base_state[component]);\n",
    "                                }\n",
    "                            }\n",
    "                        }\n",
    "\n",
    "#pragma unroll\n",
    "                        for (int component = 0; component < ODEZZA_LM_STATE_COUNT; ++component) {\n",
    "                            state[component] = fmaf(sixth_h, sum_state[component], base_state[component]);\n",
    "                        }\n",
    "                        if (statistics_phase) {\n",
    "#pragma unroll\n",
    "                            for (int index = 0; index < ODEZZA_LM_STATE_COUNT * ODEZZA_LM_LOCAL_PARAMETER_COUNT; ++index) {\n",
    "                                sensitivities[index] = fmaf(\n",
    "                                    sixth_h,\n",
    "                                    sum_sensitivity[index],\n",
    "                                    sensitivities[index]\n",
    "                                );\n",
    "                            }\n",
    "                        }\n",
    "                    }\n",
    "\n",
    "#pragma unroll\n",
    "                    for (int component = 0; component < ODEZZA_LM_STATE_COUNT; ++component) {\n",
    "                        evaluated_valid = evaluated_valid && isfinite(state[component]);\n",
    "                        const float target = reference[component * trajectory_point_count + point];\n",
    "                        const float residual_weight = weights[component * trajectory_point_count + point];\n",
    "                        evaluated_valid = evaluated_valid && isfinite(residual_weight) && residual_weight >= 0.0f;\n",
    "                        if (residual_weight == 0.0f) continue;\n",
    "                        const float residual = (state[component] - target) * residual_weight;\n",
    "                        evaluated_sse = fmaf(residual, residual, evaluated_sse);\n",
    "                        ++evaluated_residual_count;\n",
    "                        if (statistics_phase) {\n",
    "#if ODEZZA_LM_FIT_THREAD_COUNT > 1\n",
    "                            float jacobian[ODEZZA_LM_PARAMETER_COUNT];\n",
    "#pragma unroll\n",
    "                            for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "                                const int owner_lane = parameter & (ODEZZA_LM_FIT_THREAD_COUNT - 1);\n",
    "                                const int local_parameter = parameter / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                                const float owned_jacobian = lm_fit_lane == (unsigned int)owner_lane\n",
    "                                    ? sensitivities[component * ODEZZA_LM_LOCAL_PARAMETER_COUNT + local_parameter] * residual_weight\n",
    "                                    : 0.0f;\n",
    "                                jacobian[parameter] = __shfl_sync(\n",
    "                                    lm_fit_mask,\n",
    "                                    owned_jacobian,\n",
    "                                    owner_lane,\n",
    "                                    ODEZZA_LM_FIT_THREAD_COUNT\n",
    "                                );\n",
    "                            }\n",
    "#pragma unroll\n",
    "                            for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "                                if (lm_fit_lane == (unsigned int)(row & (ODEZZA_LM_FIT_THREAD_COUNT - 1))) {\n",
    "                                    const int local_gradient = row / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                                    local_optimizer[local_gradient] = fmaf(\n",
    "                                        jacobian[row],\n",
    "                                        residual,\n",
    "                                        local_optimizer[local_gradient]\n",
    "                                    );\n",
    "                                }\n",
    "#pragma unroll\n",
    "                                for (int column = row; column < ODEZZA_LM_PARAMETER_COUNT; ++column) {\n",
    "                                    const int gram_index = row * ODEZZA_LM_PARAMETER_COUNT\n",
    "                                        - row * (row - 1) / 2 + column - row;\n",
    "                                    const int optimizer_index = ODEZZA_LM_PARAMETER_COUNT + gram_index;\n",
    "                                    if (lm_fit_lane == (unsigned int)(optimizer_index & (ODEZZA_LM_FIT_THREAD_COUNT - 1))) {\n",
    "                                        const int local_gram = optimizer_index / ODEZZA_LM_FIT_THREAD_COUNT;\n",
    "                                        local_optimizer[local_gram] = fmaf(\n",
    "                                            jacobian[row],\n",
    "                                            jacobian[column],\n",
    "                                            local_optimizer[local_gram]\n",
    "                                        );\n",
    "                                    }\n",
    "                                }\n",
    "                            }\n",
    "#else\n",
    "#pragma unroll\n",
    "                            for (int row = 0; row < ODEZZA_LM_PARAMETER_COUNT; ++row) {\n",
    "                                const float jacobian_row =\n",
    "                                    sensitivities[component * ODEZZA_LM_PARAMETER_COUNT + row] * residual_weight;\n",
    "                                gradient[row] = fmaf(jacobian_row, residual, gradient[row]);\n",
    "#pragma unroll\n",
    "                                for (int column = row; column < ODEZZA_LM_PARAMETER_COUNT; ++column) {\n",
    "                                    const int gram_index = row * ODEZZA_LM_PARAMETER_COUNT\n",
    "                                        - row * (row - 1) / 2 + column - row;\n",
    "                                    const float jacobian_column =\n",
    "                                        sensitivities[component * ODEZZA_LM_PARAMETER_COUNT + column] * residual_weight;\n",
    "                                    gram[gram_index] = fmaf(jacobian_row, jacobian_column, gram[gram_index]);\n",
    "                                }\n",
    "                            }\n",
    "#endif\n",
    "                        }\n",
    "                    }\n",
    "                }\n",
    "            }\n",
    "\n",
    "            evaluated_valid = evaluated_valid && expected_start == trajectory_point_count\n",
    "                && evaluated_residual_count != 0u && isfinite(evaluated_sse);\n",
    "            if (!evaluated_valid) {\n",
    "                ++invalid_evaluations;\n",
    "                if (statistics_phase) {\n",
    "                    optimizer_valid = 0;\n",
    "                    break;\n",
    "                }\n",
    "                lambda = fminf(lambda * 10.0f, 1.0e8f);\n",
    "                continue;\n",
    "            }\n",
    "            if (statistics_phase) {\n",
    "                current_sse = evaluated_sse;\n",
    "                current_residual_count = evaluated_residual_count;\n",
    "                if (lm_iteration == 0u) {\n",
    "                    if (lm_fit_lane == 0u) initial_mse_out[fit] = current_sse / (float)current_residual_count;\n",
    "                }\n",
    "\n",
    "                continue;\n",
    "            }\n",
    "            if (evaluated_sse < current_sse) {\n",
    "                const float improvement = current_sse - evaluated_sse;\n",
    "#pragma unroll\n",
    "                for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "                    parameters[parameter] = proposal[parameter];\n",
    "                }\n",
    "                current_sse = evaluated_sse;\n",
    "                current_residual_count = evaluated_residual_count;\n",
    "                lambda = fmaxf(lambda * 0.33333334f, 1.0e-8f);\n",
    "                accepted = 1;\n",
    "                ++accepted_steps;\n",
    "                if (improvement <= 1.0e-7f * fmaxf(1.0e-12f, current_sse)) {\n",
    "                    lm_iteration = max_lm_iterations - 1u;\n",
    "                }\n",
    "            } else {\n",
    "                lambda = fminf(lambda * 10.0f, 1.0e8f);\n",
    "            }\n",
    "        }\n",
    "\n",
    "        ++completed_iterations;\n",
    "        if (!accepted || current_sse <= target_mse * (float)current_residual_count) break;\n",
    "    }\n",
    "\n",
    "    if (lm_fit_lane == 0u) {\n",
    "#pragma unroll\n",
    "        for (int parameter = 0; parameter < ODEZZA_LM_PARAMETER_COUNT; ++parameter) {\n",
    "            constants_out[fit * ODEZZA_LM_PARAMETER_COUNT + parameter] = parameters[parameter];\n",
    "        }\n",
    "        mse_out[fit] = optimizer_valid && current_residual_count != 0u\n",
    "            ? current_sse / (float)current_residual_count\n",
    "            : 3.402823466e+38f;\n",
    "        iterations_out[fit] = completed_iterations;\n",
    "        accepted_steps_out[fit] = accepted_steps;\n",
    "        factorization_attempts_out[fit] = factorization_attempts;\n",
    "        evaluations_out[fit] = evaluations; invalid_evaluations_out[fit] = invalid_evaluations;\n",
    "    }\n",
    "}\n",
    NULL};
OdezzaResult o_lm_write_body_1(OWriter *w) {
    size_t i;
    for (i = 0; o_lm_body_1[i]; ++i)
        O_RETURN_IF_ERROR(o_writer_cstr(w, o_lm_body_1[i]));
    return ODEZZA_SUCCESS;
}
