#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Charles Durham
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2026 Charles Durham
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
import argparse
import json
import re
from pathlib import Path


def ident_upper(text):
    out = re.sub(r"[^0-9A-Za-z]+", "_", text).strip("_")
    out = re.sub(r"_+", "_", out)
    return out.upper()


def ident_lower(text):
    out = re.sub(r"[^0-9A-Za-z]+", "_", text).strip("_")
    out = re.sub(r"_+", "_", out)
    return out.lower()


def enum(prefix, name):
    return prefix + ident_upper(name)


def emit_list(out, lines):
    out.extend(lines)
    out.append("")


def payload_field(encoder_type):
    if encoder_type in ("f32", "f16", "f16x2"):
        return "f"
    if encoder_type == "s32":
        return "s"
    return "u"


def arg_type_lookup(arg_types):
    return {item["name"]: item for item in arg_types}


def stack_elems_for_arg(arg_type):
    return max(int(arg_type.get("num_vec_elems", 0)), 1)


def unique_stack_requirements(arg_types, args):
    lookup = arg_type_lookup(arg_types)
    reqs = []
    reqs_by_stack = {}
    for arg_name in args:
        arg_type = lookup[arg_name]
        stack_name = arg_type["stack_type"]
        count = stack_elems_for_arg(arg_type)
        req_idx = reqs_by_stack.get(stack_name)
        if req_idx is None:
            reqs_by_stack[stack_name] = len(reqs)
            reqs.append((stack_name, count))
            continue
        prev_stack_name, prev_count = reqs[req_idx]
        reqs[req_idx] = (prev_stack_name, prev_count + count)
    return reqs


def generate(spec):
    stack_types = spec["stack_types"]
    arg_types = spec["arg_types"]
    instructions = spec["instructions"]
    special_registers = spec["special_registers"]

    stack_enum = {item["name"]: enum("STACK_PTX_STACK_TYPE_", item["name"]) for item in stack_types}
    arg_enum = {item["name"]: enum("STACK_PTX_ARG_TYPE_", item["name"]) for item in arg_types}

    instruction_names = []
    for item in instructions:
        instruction_names.append(item.get("display", item["ptx"]))
    instruction_enum = {name: enum("STACK_PTX_PTX_INSTRUCTION_", name) for name in instruction_names}

    special_names = [item.get("display", item["ptx"]) for item in special_registers]
    special_enum = {name: enum("STACK_PTX_SPECIAL_REGISTER_", name) for name in special_names}

    out = []
    emit_list(out, [
        "/* Generated by tools/generate_stack_ptx_descriptions.py. */",
        "/* Source: descriptions/stack_ptx_descriptions.json. */",
        "",
        "#pragma once",
        "#include <stack_ptx.h>",
        "",
        "#define STACK_PTX_ARRAY_NUM_ELEMS(array) (sizeof((array)) / sizeof(*(array)))",
        "",
        "#define _STACK_PTX_ENCODE_META(MI, ST) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_META, \\",
        "    .aux = (ST), \\",
        "    .payload = { .u = (MI) } \\",
        "}",
        "#define _STACK_PTX_ENCODE_META_CONSTANT(C) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_META_CONSTANT, \\",
        "    .aux = 0, \\",
        "    .payload = { .meta_constant = (C) } \\",
        "}",
        "#define _STACK_PTX_ENCODE_PTX_INSTRUCTION(IDX) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_PTX, \\",
        "    .aux = 0, \\",
        "    .payload = { .u = (IDX) } \\",
        "}",
        "#define _STACK_PTX_ENCODE_SPECIAL_REGISTER(IDX) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_SPECIAL, \\",
        "    .aux = 0, \\",
        "    .payload = { .u = (IDX) } \\",
        "}",
        "#define stack_ptx_encode_input(IDX) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_INPUT, \\",
        "    .aux = 0, \\",
        "    .payload = { .u = (IDX) } \\",
        "}",
        "#define stack_ptx_encode_return { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_RETURN, \\",
        "    .aux = 0, \\",
        "    .payload = { 0 } \\",
        "}",
        "#define stack_ptx_encode_routine(IDX) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_ROUTINE, \\",
        "    .aux = 0, \\",
        "    .payload = { .u = (IDX) } \\",
        "}",
        "#define stack_ptx_encode_store(ST, IDX) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_STORE, \\",
        "    .aux = (ST), \\",
        "    .payload = { .u = (IDX) } \\",
        "}",
        "#define stack_ptx_encode_load(IDX) { \\",
        "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_LOAD, \\",
        "    .aux = 0, \\",
        "    .payload = { .u = (IDX) } \\",
        "}",
        "#define stack_ptx_encode_meta_constant(C) _STACK_PTX_ENCODE_META_CONSTANT(C)",
        "#define stack_ptx_encode_meta_dup(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_DUP, ST)",
        "#define stack_ptx_encode_meta_yank_dup(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_YANK_DUP, ST)",
        "#define stack_ptx_encode_meta_swap(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_SWAP, ST)",
        "#define stack_ptx_encode_meta_swap_with(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_SWAP_WITH, ST)",
        "#define stack_ptx_encode_meta_replace(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_REPLACE, ST)",
        "#define stack_ptx_encode_meta_drop(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_DROP, ST)",
        "#define stack_ptx_encode_meta_clear(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_CLEAR, ST)",
        "#define stack_ptx_encode_meta_rotate(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_ROTATE, ST)",
        "#define stack_ptx_encode_meta_reverse(ST) _STACK_PTX_ENCODE_META(STACK_PTX_META_INSTRUCTION_REVERSE, ST)",
    ])

    out.append("typedef enum {")
    for item in stack_types:
        out.append(f"    {stack_enum[item['name']]},")
    out.append("    STACK_PTX_STACK_TYPE_NUM_ENUMS")
    out.append("} StackPtxStackType;")
    out.append("")

    out.append("typedef enum {")
    for item in arg_types:
        out.append(f"    {arg_enum[item['name']]},")
    out.append("    STACK_PTX_ARG_TYPE_NUM_ENUMS")
    out.append("} StackPtxArgType;")
    out.append("")
    out.append("#define STACK_PTX_ARG_TYPE_NONE STACK_PTX_ARG_TYPE_NUM_ENUMS")
    out.append("")

    out.append("typedef enum {")
    for name in instruction_names:
        out.append(f"    {instruction_enum[name]},")
    out.append("    STACK_PTX_PTX_INSTRUCTION_NUM_ENUMS")
    out.append("} StackPtxPtxInstruction;")
    out.append("")

    out.append("typedef enum {")
    for name in special_names:
        out.append(f"    {special_enum[name]},")
    out.append("    STACK_PTX_SPECIAL_REGISTER_NUM_ENUMS")
    out.append("} StackPtxSpecialRegister;")
    out.append("")

    out.append("static const char* stack_ptx_stack_literal_prefixes[] = {")
    for item in stack_types:
        out.append(f"    [{stack_enum[item['name']]}] = \"{item['literal_prefix']}\",")
    out.append("};")
    out.append("")

    out.append("static const StackPtxArgTypeInfo stack_ptx_arg_type_info[] = {")
    for item in arg_types:
        stack_name = item["stack_type"]
        num_vec_elems = int(item.get("num_vec_elems", 0))
        out.append(f"    [{arg_enum[item['name']]}] = {{ {stack_enum[stack_name]}, {num_vec_elems} }},")
    out.append("};")
    out.append("")

    for item in stack_types:
        encoder_type = item.get("encoder_type")
        if not encoder_type:
            continue
        name = ident_lower(item["name"])
        field = payload_field(encoder_type)
        out.extend([
            f"#define stack_ptx_encode_constant_{name}(C) {{ \\",
            "    .instruction_type = STACK_PTX_INSTRUCTION_TYPE_CONSTANT, \\",
            f"    .aux = {stack_enum[item['name']]}, \\",
            f"    .payload = {{ .{field} = (C) }} \\",
            "}",
            "",
        ])

    for item, name in zip(instructions, instruction_names):
        out.append(
            "static const StackPtxInstruction "
            f"stack_ptx_encode_ptx_instruction_{ident_lower(name)} = "
            f"_STACK_PTX_ENCODE_PTX_INSTRUCTION({instruction_enum[name]});"
        )
    out.append("")

    out.append("static const StackPtxPtxInstructionDescriptor stack_ptx_ptx_instruction_descriptors[] = {")
    for item, name in zip(instructions, instruction_names):
        args = item.get("args", [])
        rets = item.get("rets", [])
        arg_values = [arg_enum[args[i]] if i < len(args) else "STACK_PTX_ARG_TYPE_NONE" for i in range(4)]
        ret_values = [arg_enum[rets[i]] if i < len(rets) else "STACK_PTX_ARG_TYPE_NONE" for i in range(2)]
        aligned = "true" if item.get("aligned", False) else "false"
        reqs = unique_stack_requirements(arg_types, args)
        out.append(f"    [{instruction_enum[name]}] = {{")
        out.append(f"        .arg_types = {{ {arg_values[0]}, {arg_values[1]}, {arg_values[2]}, {arg_values[3]} }},")
        out.append(f"        .ret_types = {{ {ret_values[0]}, {ret_values[1]} }},")
        out.append(f"        .num_unique_stacks = {len(reqs)},")
        out.append(f"        .is_aligned = {aligned},")
        out.append("        .unique_stacks = {")
        for stack_name, count in reqs:
            out.append(f"            {{ {stack_enum[stack_name]}, {count} }},")
        for _ in range(4 - len(reqs)):
            out.append("            { 0, 0 },")
        out.append("        },")
        out.append("    },")
    out.append("};")
    out.append("")

    out.append("#if defined(__GNUC__) || defined(__clang__)")
    out.append("#define STACK_PTX_DESC_UNUSED __attribute__((unused))")
    out.append("#else")
    out.append("#define STACK_PTX_DESC_UNUSED")
    out.append("#endif")
    out.append("")
    out.append("STACK_PTX_DESC_UNUSED static const char* stack_ptx_ptx_instruction_display_names[] = {")
    for item, name in zip(instructions, instruction_names):
        display = item.get("display", item["ptx"])
        out.append(f"    [{instruction_enum[name]}] = \"{display}\",")
    out.append("};")
    out.append("")

    out.append("static const char* stack_ptx_ptx_instruction_ptx_names[] = {")
    for item, name in zip(instructions, instruction_names):
        out.append(f"    [{instruction_enum[name]}] = \"{item['ptx']}\",")
    out.append("};")
    out.append("")

    out.append("static const StackPtxInstruction stack_ptx_ptx_instructions[] = {")
    for name in instruction_names:
        out.append(
            f"    [{instruction_enum[name]}] = "
            f"stack_ptx_encode_ptx_instruction_{ident_lower(name)},"
        )
    out.append("};")
    out.append("")

    for item, name in zip(special_registers, special_names):
        out.append(
            "static const StackPtxInstruction "
            f"stack_ptx_encode_special_register_{ident_lower(name)} = "
            f"_STACK_PTX_ENCODE_SPECIAL_REGISTER({special_enum[name]});"
        )
    out.append("")

    out.append("static const StackPtxSpecialRegisterDescriptor stack_ptx_special_register_descriptors[] = {")
    for item, name in zip(special_registers, special_names):
        out.append(f"    [{special_enum[name]}] = {{ {arg_enum[item['arg_type']]} }},")
    out.append("};")
    out.append("")

    out.append("STACK_PTX_DESC_UNUSED static const char* stack_ptx_special_register_display_names[] = {")
    for item, name in zip(special_registers, special_names):
        display = item.get("display", item["ptx"])
        out.append(f"    [{special_enum[name]}] = \"{display}\",")
    out.append("};")
    out.append("")

    out.append("static const char* stack_ptx_special_register_ptx_names[] = {")
    for item, name in zip(special_registers, special_names):
        out.append(f"    [{special_enum[name]}] = \"{item['ptx']}\",")
    out.append("};")
    out.append("")

    out.append("static const StackPtxInstruction stack_ptx_special_registers[] = {")
    for name in special_names:
        out.append(
            f"    [{special_enum[name]}] = "
            f"stack_ptx_encode_special_register_{ident_lower(name)},"
        )
    out.append("};")
    out.append("")

    out.extend([
        "static const StackPtxStackInfo stack_ptx_stack_info = {",
        "    .ptx_instruction_strings = stack_ptx_ptx_instruction_ptx_names,",
        "    .ptx_instruction_descriptors = stack_ptx_ptx_instruction_descriptors,",
        "    .num_ptx_instructions = STACK_PTX_PTX_INSTRUCTION_NUM_ENUMS,",
        "    .special_register_strings = stack_ptx_special_register_ptx_names,",
        "    .special_register_descriptors = stack_ptx_special_register_descriptors,",
        "    .num_special_registers = STACK_PTX_SPECIAL_REGISTER_NUM_ENUMS,",
        "    .stack_literal_prefixes = stack_ptx_stack_literal_prefixes,",
        "    .num_stacks = STACK_PTX_STACK_TYPE_NUM_ENUMS,",
        "    .arg_type_info = stack_ptx_arg_type_info,",
        "    .num_arg_types = STACK_PTX_ARG_TYPE_NUM_ENUMS",
        "};",
        "",
        "#undef STACK_PTX_DESC_UNUSED",
    ])

    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    with open(args.input, "r", encoding="utf-8") as src:
        spec = json.load(src)

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate(spec), encoding="utf-8")


if __name__ == "__main__":
    main()
