/*
 * SPDX-FileCopyrightText: 2026 Charles Durham
 * SPDX-License-Identifier: MIT
 *
 * MIT License
 *
 * Copyright (c) 2026 Charles Durham
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Generated by secant_generate_cuda. Do not edit.

extern "C" __global__
void secant_static_column_materialize_000(
    const float* __restrict__ input,
    unsigned long long input_leading_dimension,
    unsigned long long num_rows,
    float* __restrict__ output,
    unsigned long long output_leading_dimension
) {
    const unsigned long long row = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
    if (row >= num_rows) {
        return;
    }

    float input0 = input[(unsigned long long)0 * input_leading_dimension + row];
    float input1 = input[(unsigned long long)1 * input_leading_dimension + row];
    float input2 = input[(unsigned long long)2 * input_leading_dimension + row];
    float input3 = input[(unsigned long long)3 * input_leading_dimension + row];
    float input4 = input[(unsigned long long)4 * input_leading_dimension + row];
    float input5 = input[(unsigned long long)5 * input_leading_dimension + row];
    float input6 = input[(unsigned long long)6 * input_leading_dimension + row];
    float input7 = input[(unsigned long long)7 * input_leading_dimension + row];

    float marked0 __attribute__((unused));
    float marked1 __attribute__((unused));
    float marked2 __attribute__((unused));
    float marked3 __attribute__((unused));
    float marked4 __attribute__((unused));
    float marked5 __attribute__((unused));
    float marked6 __attribute__((unused));
    float marked7 __attribute__((unused));
    float result0;
    float result1;
    float keepalive __attribute__((unused));
    asm volatile(
        "{\n\t"
        ".reg .u32 keepalive_address;\n\t"
        "brkpt;\n\t"
        "add.rn.ftz.f32 %0, %11, 0f7fc0ffee;\n\t"
        "add.rn.ftz.f32 %1, %12, 0f7fc0ffef;\n\t"
        "add.rn.ftz.f32 %2, %13, 0f7fc0fff0;\n\t"
        "add.rn.ftz.f32 %3, %14, 0f7fc0fff1;\n\t"
        "add.rn.ftz.f32 %4, %15, 0f7fc0fff2;\n\t"
        "add.rn.ftz.f32 %5, %16, 0f7fc0fff3;\n\t"
        "add.rn.ftz.f32 %6, %17, 0f7fc0fff4;\n\t"
        "add.rn.ftz.f32 %7, %18, 0f7fc0fff5;\n\t"
        "brkpt;\n\t"
        "add.rn.ftz.f32 %0, %0, %1;\n\t"
        "add.rn.ftz.f32 %2, %2, %3;\n\t"
        "add.rn.ftz.f32 %0, %0, %2;\n\t"
        "add.rn.ftz.f32 %4, %4, %5;\n\t"
        "add.rn.ftz.f32 %6, %6, %7;\n\t"
        "add.rn.ftz.f32 %4, %4, %6;\n\t"
        "add.rn.ftz.f32 %0, %0, %4;\n\t"
        "add.rn.ftz.f32 %8, %0, 0f7fc0fff6;\n\t"
        "add.rn.ftz.f32 %9, %0, 0f7fc0fff7;\n\t"
        "brkpt;\n\t"
        "add.rn.ftz.f32 %10, %8, %9;\n\t"
        "add.rn.ftz.f32 %10, %10, %11;\n\t"
        "add.rn.ftz.f32 %10, %10, %12;\n\t"
        "add.rn.ftz.f32 %10, %10, %13;\n\t"
        "add.rn.ftz.f32 %10, %10, %14;\n\t"
        "add.rn.ftz.f32 %10, %10, %15;\n\t"
        "add.rn.ftz.f32 %10, %10, %16;\n\t"
        "add.rn.ftz.f32 %10, %10, %17;\n\t"
        "add.rn.ftz.f32 %10, %10, %18;\n\t"
        "mov.u32 keepalive_address, 0;\n\t"
        "st.volatile.shared.f32 [keepalive_address], %10;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "}\n\t"
        : "=&f"(marked0), "=&f"(marked1), "=&f"(marked2), "=&f"(marked3), "=&f"(marked4), "=&f"(marked5), "=&f"(marked6), "=&f"(marked7), "=&f"(result0), "=&f"(result1), "=&f"(keepalive)
        : "f"(input0), "f"(input1), "f"(input2), "f"(input3), "f"(input4), "f"(input5), "f"(input6), "f"(input7)
        : "memory");

    output[(unsigned long long)0 * output_leading_dimension + row] = result0;
    output[(unsigned long long)1 * output_leading_dimension + row] = result1;
}

extern "C" __global__
void secant_static_column_materialize_001(
    const float* __restrict__ input,
    unsigned long long input_leading_dimension,
    unsigned long long num_rows,
    float* __restrict__ output,
    unsigned long long output_leading_dimension
) {
    const unsigned long long row = (unsigned long long)blockIdx.x * blockDim.x + threadIdx.x;
    if (row >= num_rows) {
        return;
    }

    float input0 = input[(unsigned long long)0 * input_leading_dimension + row];
    float input1 = input[(unsigned long long)1 * input_leading_dimension + row];
    float input2 = input[(unsigned long long)2 * input_leading_dimension + row];
    float input3 = input[(unsigned long long)3 * input_leading_dimension + row];
    float input4 = input[(unsigned long long)4 * input_leading_dimension + row];
    float input5 = input[(unsigned long long)5 * input_leading_dimension + row];
    float input6 = input[(unsigned long long)6 * input_leading_dimension + row];
    float input7 = input[(unsigned long long)7 * input_leading_dimension + row];

    float marked0 __attribute__((unused));
    float marked1 __attribute__((unused));
    float marked2 __attribute__((unused));
    float marked3 __attribute__((unused));
    float marked4 __attribute__((unused));
    float marked5 __attribute__((unused));
    float marked6 __attribute__((unused));
    float marked7 __attribute__((unused));
    float result0;
    float result1;
    float keepalive __attribute__((unused));
    asm volatile(
        "{\n\t"
        ".reg .u32 keepalive_address;\n\t"
        "brkpt;\n\t"
        "add.rn.ftz.f32 %0, %11, 0f7fc0fff8;\n\t"
        "add.rn.ftz.f32 %1, %12, 0f7fc0fff9;\n\t"
        "add.rn.ftz.f32 %2, %13, 0f7fc0fffa;\n\t"
        "add.rn.ftz.f32 %3, %14, 0f7fc0fffb;\n\t"
        "add.rn.ftz.f32 %4, %15, 0f7fc0fffc;\n\t"
        "add.rn.ftz.f32 %5, %16, 0f7fc0fffd;\n\t"
        "add.rn.ftz.f32 %6, %17, 0f7fc0fffe;\n\t"
        "add.rn.ftz.f32 %7, %18, 0f7fc0ffff;\n\t"
        "brkpt;\n\t"
        "add.rn.ftz.f32 %0, %0, %1;\n\t"
        "add.rn.ftz.f32 %2, %2, %3;\n\t"
        "add.rn.ftz.f32 %0, %0, %2;\n\t"
        "add.rn.ftz.f32 %4, %4, %5;\n\t"
        "add.rn.ftz.f32 %6, %6, %7;\n\t"
        "add.rn.ftz.f32 %4, %4, %6;\n\t"
        "add.rn.ftz.f32 %0, %0, %4;\n\t"
        "add.rn.ftz.f32 %8, %0, 0f7fc10000;\n\t"
        "add.rn.ftz.f32 %9, %0, 0f7fc10001;\n\t"
        "brkpt;\n\t"
        "add.rn.ftz.f32 %10, %8, %9;\n\t"
        "add.rn.ftz.f32 %10, %10, %11;\n\t"
        "add.rn.ftz.f32 %10, %10, %12;\n\t"
        "add.rn.ftz.f32 %10, %10, %13;\n\t"
        "add.rn.ftz.f32 %10, %10, %14;\n\t"
        "add.rn.ftz.f32 %10, %10, %15;\n\t"
        "add.rn.ftz.f32 %10, %10, %16;\n\t"
        "add.rn.ftz.f32 %10, %10, %17;\n\t"
        "add.rn.ftz.f32 %10, %10, %18;\n\t"
        "mov.u32 keepalive_address, 0;\n\t"
        "st.volatile.shared.f32 [keepalive_address], %10;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "brkpt;\n\t"
        "}\n\t"
        : "=&f"(marked0), "=&f"(marked1), "=&f"(marked2), "=&f"(marked3), "=&f"(marked4), "=&f"(marked5), "=&f"(marked6), "=&f"(marked7), "=&f"(result0), "=&f"(result1), "=&f"(keepalive)
        : "f"(input0), "f"(input1), "f"(input2), "f"(input3), "f"(input4), "f"(input5), "f"(input6), "f"(input7)
        : "memory");

    output[(unsigned long long)0 * output_leading_dimension + row] = result0;
    output[(unsigned long long)1 * output_leading_dimension + row] = result1;
}
