# SPDX-FileCopyrightText: 2026 Charles Durham
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2026 Charles Durham
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""Embed small shared CUDA sources as C string arrays; no build-time CUDA dependency."""
import json
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
for name,symbol in [('o_sampled_constants.cuh','o_sampled_source'),('o_philox.cu','o_philox_source')]:
    path=root/'src'/name
    if not path.exists():continue
    text='/* Generated by tests/embed_cuda_source.py. */\nstatic const char *const '+symbol+'[] = {\n'
    text+=''.join('    '+json.dumps(line)+',\n' for line in path.read_text().splitlines(keepends=True))+'};\n'
    target=root/'src'/(path.stem+'_source.h')
    if '--check' in sys.argv:
        if target.read_text()!=text:raise SystemExit(str(target)+' is stale')
    else:target.write_text(text)
