# SPDX-FileCopyrightText: 2026 Charles Durham
# SPDX-License-Identifier: MIT
#
# MIT License
#
# Copyright (c) 2026 Charles Durham
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
"""Generate/check the C embedding of the reducer's NVRTC source."""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
source = (root / 'core/o_score_reduce.cu').read_text()
text = '/* Generated by tests/embed_score_reducer.py; edit o_score_reduce.cu. */\n'
text += 'static const char *const o_reduce_source[] = {\n'
text += ''.join('    '+json.dumps(line)+' ,\n' for line in source.splitlines(keepends=True))
text += '};\n'
target = root / 'core/o_score_reduce_source.h'
if '--check' in sys.argv:
    if target.read_text() != text:
        raise SystemExit('reducer embedding is stale')
else:
    target.write_text(text)
